name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Deploy-to-EC2:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
      - name: List files in the repository
        run: |
          ssh 13.223.80.129
          cd ci-cd-pipeline-test
          git pull
          npm install
          npm start
      - run: echo "🍏 This job's status is ${{ job.status }}."
